### ISSUE TITLE
Install on OSX help

### ISSUE THREAD

**Issue by dlg0** [mgalloy/ridl#16]
I'd like to try rIDL. However, I'm unable to get it to build due to dependancies, i.e., ...

```
dlg-macpro:ridl dg6$ ./install_ridl.sh
./install_ridl.sh: line 3: cleanconf.sh: command not found
-- Pointer size: 64-bit build
-- Install location: /Users/dg6/software/ridl-97b9ad6
-- Found components for IDL
-- IDL_VERSION     = 8.4.0
-- IDL_EXECUTABLE  = /usr/local/exelis/idl84/bin/idl
-- IDL_INCLUDE_DIR = /usr/local/exelis/idl84/external/include
-- IDL_LIBRARY     = /usr/local/exelis/idl84
CMake Error at mgcmake/Modules/FindReadline.cmake:47 (message):
  Could not find GNU Readline
Call Stack (most recent call first):
  CMakeLists.txt:31 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/dg6/code/ridl/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `onlinehelp'.  Stop.
make: *** No rule to make target `install'.  Stop.
ln -s -f -v /Users/dg6/software/ridl-97b9ad6/ /Users/dg6/software/ridl
ln: /Users/dg6/software/ridl: No such file or directory
```

so I add the macports installed readline location ...

```
dlg-macpro:ridl dg6$ cmake -DIDL_LIBRARY=/usr/local/exelis/idl84 -DIDL_EXECUTABLE=/usr/local/exelis/idl84/bin/idl -DIDL_INCLUDE_DIR=/usr/local/exelis/idl84/external/include -DReadline_INCLUDE_DIR=/opt/local/include -DReadline_LIBRARY=/opt/local/lib/libreadline.dylib .
-- Pointer size: 64-bit build
-- Install location: /Users/dg6/software/ridl-97b9ad6
-- Found components for IDL
-- IDL_VERSION     = 8.4.0
-- IDL_EXECUTABLE  = /usr/local/exelis/idl84/bin/idl
-- IDL_INCLUDE_DIR = /usr/local/exelis/idl84/external/include
-- IDL_LIBRARY     = /usr/local/exelis/idl84
-- Found GNU Readline: /opt/local/lib/libreadline.dylib
-- Configuring done
WARNING: Target "ridl" requests linking to directory "/usr/local/exelis/idl84".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /Users/dg6/code/ridl
```
```
dlg-macpro:ridl dg6$ make
-- Pointer size: 64-bit build
-- Install location: /Users/dg6/software/ridl-97b9ad6
-- Found components for IDL
-- IDL_VERSION     = 8.4.0
-- IDL_EXECUTABLE  = /usr/local/exelis/idl84/bin/idl
-- IDL_INCLUDE_DIR = /usr/local/exelis/idl84/external/include
-- IDL_LIBRARY     = /usr/local/exelis/idl84
-- Found GNU Readline: /opt/local/lib/libreadline.dylib
-- Configuring done
WARNING: Target "ridl" requests linking to directory "/usr/local/exelis/idl84".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /Users/dg6/code/ridl
Linking C executable ridl
ld: warning: directory not found for option '-L/usr/X11/lib'
ld: library not found for -lXm
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/ridl] Error 1
make[1]: *** [src/CMakeFiles/ridl.dir/all] Error 2
make: *** [all] Error 2
```

so then I alter `src/CMakeLists.txt` to link to the macports installed libXm

```
 31 # Freetype library not included in Mac OS X distribution of IDL
 32 if (UNIX AND APPLE)
 33         set(rIDL_LD_FLAGS "-L${IDL_LIBRARY_PATH} -lXm -L/usr/X11/lib -L/opt/local/lib -lfreetype -lMesaGL6_2 -lMesaGLU6_2 -lOS 34 else ()
 35   set(rIDL_LD_FLAGS "")
 36 endif ()
```

```
dlg-macpro:ridl dg6$ make
[ 12%] Building C object src/CMakeFiles/ridl.dir/ridl.c.o
[ 25%] Building C object src/CMakeFiles/ridl.dir/ridl_completion.c.o
[ 37%] Building C object src/CMakeFiles/ridl.dir/ridl_history.c.o
[ 50%] Building C object src/CMakeFiles/ridl.dir/ridl_logging.c.o
[ 62%] Building C object src/CMakeFiles/ridl.dir/ridl_magic.c.o
[ 75%] Building C object src/CMakeFiles/ridl.dir/ridl_preferences.c.o
[ 87%] Building C object src/CMakeFiles/ridl.dir/ridl_idlpreferences.c.o
[100%] Building C object src/CMakeFiles/ridl.dir/ridl_strings.c.o
Linking C executable ridl
ld: warning: directory not found for option '-L/usr/X11/lib'
ld: library not found for -lMesaGL6_2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/ridl] Error 1
make[1]: *** [src/CMakeFiles/ridl.dir/all] Error 2
make: *** [all] Error 2
```

But I don't know where to get these MesaGL6_2 libs, and have probably strayed too far.

Any tips?

Thanks.

**Comment by mgalloy** [comment]
No need to modify the CMakeLists.txt, just pass the params to the make
command at configure time:

cmake -DReadline_INCLUDE_DIR:PATH=/usr/local/opt/readline/include
-DReadline_LIBRARY:FILEPATH=/usr/local/opt/readline/lib/libreadline.dylib .

I think this should help your problem of finding the MesaGL libs.

-Mike


On Tue, Aug 4, 2015 at 7:29 AM, David L Green <notifications@github.com>
wrote:

> I'd like to try rIDL. However, I'm unable to get it to build due to
> dependancies, i.e., ...
>
> dlg-macpro:ridl dg6$ ./install_ridl.sh
> ./install_ridl.sh: line 3: cleanconf.sh: command not found
> -- Pointer size: 64-bit build
> -- Install location: /Users/dg6/software/ridl-97b9ad6
> -- Found components for IDL
> -- IDL_VERSION     = 8.4.0
> -- IDL_EXECUTABLE  = /usr/local/exelis/idl84/bin/idl
> -- IDL_INCLUDE_DIR = /usr/local/exelis/idl84/external/include
> -- IDL_LIBRARY     = /usr/local/exelis/idl84
> CMake Error at mgcmake/Modules/FindReadline.cmake:47 (message):
>   Could not find GNU Readline
> Call Stack (most recent call first):
>   CMakeLists.txt:31 (find_package)
>
>
> -- Configuring incomplete, errors occurred!
> See also "/Users/dg6/code/ridl/CMakeFiles/CMakeOutput.log".
> make: *** No targets specified and no makefile found.  Stop.
> make: *** No rule to make target `onlinehelp'.  Stop.
> make: *** No rule to make target `install'.  Stop.
> ln -s -f -v /Users/dg6/software/ridl-97b9ad6/ /Users/dg6/software/ridl
> ln: /Users/dg6/software/ridl: No such file or directory
>
> so I add the macports installed readline location ...
>
> dlg-macpro:ridl dg6$ cmake -DIDL_LIBRARY=/usr/local/exelis/idl84 -DIDL_EXECUTABLE=/usr/local/exelis/idl84/bin/idl -DIDL_INCLUDE_DIR=/usr/local/exelis/idl84/external/include -DReadline_INCLUDE_DIR=/opt/local/include -DReadline_LIBRARY=/opt/local/lib/libreadline.dylib .
> -- Pointer size: 64-bit build
> -- Install location: /Users/dg6/software/ridl-97b9ad6
> -- Found components for IDL
> -- IDL_VERSION     = 8.4.0
> -- IDL_EXECUTABLE  = /usr/local/exelis/idl84/bin/idl
> -- IDL_INCLUDE_DIR = /usr/local/exelis/idl84/external/include
> -- IDL_LIBRARY     = /usr/local/exelis/idl84
> -- Found GNU Readline: /opt/local/lib/libreadline.dylib
> -- Configuring done
> WARNING: Target "ridl" requests linking to directory "/usr/local/exelis/idl84".  Targets may link only to libraries.  CMake is dropping the item.
> -- Generating done
> -- Build files have been written to: /Users/dg6/code/ridl
>
> dlg-macpro:ridl dg6$ make
> -- Pointer size: 64-bit build
> -- Install location: /Users/dg6/software/ridl-97b9ad6
> -- Found components for IDL
> -- IDL_VERSION     = 8.4.0
> -- IDL_EXECUTABLE  = /usr/local/exelis/idl84/bin/idl
> -- IDL_INCLUDE_DIR = /usr/local/exelis/idl84/external/include
> -- IDL_LIBRARY     = /usr/local/exelis/idl84
> -- Found GNU Readline: /opt/local/lib/libreadline.dylib
> -- Configuring done
> WARNING: Target "ridl" requests linking to directory "/usr/local/exelis/idl84".  Targets may link only to libraries.  CMake is dropping the item.
> -- Generating done
> -- Build files have been written to: /Users/dg6/code/ridl
> Linking C executable ridl
> ld: warning: directory not found for option '-L/usr/X11/lib'
> ld: library not found for -lXm
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [src/ridl] Error 1
> make[1]: *** [src/CMakeFiles/ridl.dir/all] Error 2
> make: *** [all] Error 2
>
> so then I alter src/CMakeLists.txt to link to the macports installed libXm
>
>  31 # Freetype library not included in Mac OS X distribution of IDL
>  32 if (UNIX AND APPLE)
>  33         set(rIDL_LD_FLAGS "-L${IDL_LIBRARY_PATH} -lXm -L/usr/X11/lib -L/opt/local/lib -lfreetype -lMesaGL6_2 -lMesaGLU6_2 -lOS 34 else ()
>  35   set(rIDL_LD_FLAGS "")
>  36 endif ()
>
> dlg-macpro:ridl dg6$ make
> [ 12%] Building C object src/CMakeFiles/ridl.dir/ridl.c.o
> [ 25%] Building C object src/CMakeFiles/ridl.dir/ridl_completion.c.o
> [ 37%] Building C object src/CMakeFiles/ridl.dir/ridl_history.c.o
> [ 50%] Building C object src/CMakeFiles/ridl.dir/ridl_logging.c.o
> [ 62%] Building C object src/CMakeFiles/ridl.dir/ridl_magic.c.o
> [ 75%] Building C object src/CMakeFiles/ridl.dir/ridl_preferences.c.o
> [ 87%] Building C object src/CMakeFiles/ridl.dir/ridl_idlpreferences.c.o
> [100%] Building C object src/CMakeFiles/ridl.dir/ridl_strings.c.o
> Linking C executable ridl
> ld: warning: directory not found for option '-L/usr/X11/lib'
> ld: library not found for -lMesaGL6_2
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [src/ridl] Error 1
> make[1]: *** [src/CMakeFiles/ridl.dir/all] Error 2
> make: *** [all] Error 2
>
> But I don't know where to get these MesaGL6_2 libs, and have probably
> strayed too far.
>
> Any tips?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgalloy/ridl/issues/16>.
>



-- 
Michael Galloy
www.michaelgalloy.com
Modern IDL: A Guide to IDL Programming (http://modernidl.idldev.com)

**Comment by dlg0** [comment]
Thanks. I was able to get it to compile.
