### ISSUE TITLE
defining `!PATH` in session produces a Segmentation Fault

### ISSUE THREAD

**Issue by dpshelio** [mgalloy/ridl#18]
On a Linux system, with IDL 8.4 and ridl 0.2.0 [Build: 03/13/15]

Trying the following in plain IDL,
```idl
IDL> !path = "~/Documents:"+!path
IDL> print, !path                
~/Documents:...
```
works as expected. However it produces a Segmentation fault when used in ridl:
```idl
[130]> !path = "~/Documents:"+!path
/home/.../bin/ridl: line 22: 17517 Segmentation fault      /home/.../ridl/install/bin/ridl $@
```

However, if set in the `$IDL_STARTUP` env variable, it works as expected:

`idlrc` content:
```idl
!path="~/Documents:" + !path
print,"this is my machine!"
```
idl session:
```idl
this is my machine!
[132]> print,!path
/home/.../ridl/install/share/idl/:~/Documents:/usr/local/...
```

There are some paths I need to set manually some times, so using the `$IDL_STARTUP` file is not a nice workaround solution.

**Comment by mgalloy** [comment]
I have a temporary fix in fafa3183537f52c9c0b0953e83fb0fb735bbbd76. Something is wrong in some of the tab completion finding routines, but I'm not sure what it is yet. This temporary fix should stop the set fault, but limit tab completion on routines in the path.
